// ════════════════════════════════════════════════════════════════════════════
// PDF EXPORT SERVICE
// For exporting vault documents, stories, and legacy content
// ════════════════════════════════════════════════════════════════════════════

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

// ────────────────────────────────────────────────────────────────────────────
// TYPES
// ────────────────────────────────────────────────────────────────────────────

interface VaultItem {
  name: string;
  type: string;
  description?: string;
  importance?: string;
  createdAt?: string;
}

interface FinanceItem extends VaultItem {
  institutionName: string;
  accountNumber?: string;
  balance?: number;
  currency?: string;
  nominees?: Array<{ name: string; relationship: string }>;
}

interface InsuranceItem extends VaultItem {
  provider: string;
  policyNumber?: string;
  coverageAmount?: number;
  premium?: number;
  premiumFrequency?: string;
  endDate?: string;
  nominees?: Array<{ name: string; relationship: string }>;
}

interface Story {
  title: string;
  content: string;
  category?: string;
  createdAt?: string;
  excerpt?: string;
}

interface ExportOptions {
  title?: string;
  subtitle?: string;
  includeDate?: boolean;
  userName?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// PDF STYLING
// ────────────────────────────────────────────────────────────────────────────

const COLORS = {
  sage: [107, 142, 97] as [number, number, number],
  sageDark: [85, 113, 77] as [number, number, number],
  text: [55, 55, 55] as [number, number, number],
  muted: [120, 120, 120] as [number, number, number],
  light: [245, 247, 244] as [number, number, number],
};

function addHeader(
  doc: jsPDF,
  title: string,
  subtitle?: string,
  userName?: string
) {
  // Header background
  doc.setFillColor(...COLORS.sage);
  doc.rect(0, 0, 220, 45, "F");

  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("AfterMe", 20, 22);

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(title, 20, 35);

  // Subtitle and date on right
  doc.setFontSize(10);
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  if (subtitle) {
    doc.text(subtitle, 190, 22, { align: "right" });
  }
  if (userName) {
    doc.text(`Prepared for: ${userName}`, 190, 30, { align: "right" });
  }
  doc.text(date, 190, 38, { align: "right" });

  return 55; // Return starting Y position for content
}

function addFooter(doc: jsPDF, pageNumber: number) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text(
    `Page ${pageNumber} | Generated by AfterMe - Your Digital Legacy`,
    105,
    pageHeight - 10,
    { align: "center" }
  );
}

function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(...COLORS.light);
  doc.rect(15, y - 5, 180, 12, "F");
  doc.setTextColor(...COLORS.sageDark);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 20, y + 3);
  return y + 15;
}

// ────────────────────────────────────────────────────────────────────────────
// VAULT EXPORT
// ────────────────────────────────────────────────────────────────────────────

export function exportVaultToPDF(
  financeItems: FinanceItem[],
  insuranceItems: InsuranceItem[],
  options: ExportOptions = {}
): jsPDF {
  const doc = new jsPDF();
  let y = addHeader(
    doc,
    options.title || "Vault Summary",
    "Financial & Insurance Overview",
    options.userName
  );

  // Finance Section
  if (financeItems.length > 0) {
    y = addSectionTitle(doc, "Financial Accounts", y);

    const financeData = financeItems.map((item) => [
      item.name,
      item.type,
      item.institutionName,
      item.accountNumber ? `****${item.accountNumber.slice(-4)}` : "-",
      item.balance
        ? new Intl.NumberFormat("en-IN", {
            style: "currency",
            currency: item.currency || "INR",
          }).format(item.balance)
        : "-",
      item.nominees?.map((n) => n.name).join(", ") || "None",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Name", "Type", "Institution", "Account", "Balance", "Nominees"]],
      body: financeData,
      theme: "striped",
      headStyles: {
        fillColor: COLORS.sage,
        textColor: 255,
        fontStyle: "bold",
      },
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 25 },
        2: { cellWidth: 35 },
        3: { cellWidth: 25 },
        4: { cellWidth: 30 },
        5: { cellWidth: 30 },
      },
    });

    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  }

  // Insurance Section
  if (insuranceItems.length > 0) {
    // Check if we need a new page
    if (y > 200) {
      doc.addPage();
      y = 20;
    }

    y = addSectionTitle(doc, "Insurance Policies", y);

    const insuranceData = insuranceItems.map((item) => [
      item.name,
      item.type,
      item.provider,
      item.policyNumber ? `****${item.policyNumber.slice(-4)}` : "-",
      item.coverageAmount
        ? new Intl.NumberFormat("en-IN", {
            style: "currency",
            currency: "INR",
          }).format(item.coverageAmount)
        : "-",
      item.premium
        ? `${new Intl.NumberFormat("en-IN", {
            style: "currency",
            currency: "INR",
          }).format(item.premium)}/${item.premiumFrequency || "yr"}`
        : "-",
      item.endDate
        ? new Date(item.endDate).toLocaleDateString("en-IN")
        : "-",
    ]);

    autoTable(doc, {
      startY: y,
      head: [
        ["Name", "Type", "Provider", "Policy #", "Coverage", "Premium", "Expiry"],
      ],
      body: insuranceData,
      theme: "striped",
      headStyles: {
        fillColor: COLORS.sage,
        textColor: 255,
        fontStyle: "bold",
      },
      styles: {
        fontSize: 8,
        cellPadding: 2,
      },
    });
  }

  // Add page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i);
  }

  return doc;
}

// ────────────────────────────────────────────────────────────────────────────
// STORIES EXPORT
// ────────────────────────────────────────────────────────────────────────────

export function exportStoriesToPDF(
  stories: Story[],
  options: ExportOptions = {}
): jsPDF {
  const doc = new jsPDF();
  let currentPage = 1;

  stories.forEach((story, index) => {
    if (index > 0) {
      doc.addPage();
      currentPage++;
    }

    let y = 20;

    // Story header
    doc.setFillColor(...COLORS.sage);
    doc.rect(0, 0, 220, 35, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(story.title, 20, 18);

    if (story.category) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(story.category.toUpperCase(), 20, 28);
    }

    if (story.createdAt) {
      doc.setFontSize(9);
      doc.text(
        new Date(story.createdAt).toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        }),
        190,
        28,
        { align: "right" }
      );
    }

    y = 50;

    // Story content
    doc.setTextColor(...COLORS.text);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    // Split content into lines that fit the page
    const pageWidth = doc.internal.pageSize.width;
    const margins = 40;
    const maxWidth = pageWidth - margins;
    const lineHeight = 7;
    const pageHeight = doc.internal.pageSize.height - 30;

    // Strip HTML tags from content
    const plainText = story.content.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
    const lines = doc.splitTextToSize(plainText, maxWidth);

    lines.forEach((line: string) => {
      if (y > pageHeight) {
        doc.addPage();
        currentPage++;
        y = 20;
      }
      doc.text(line, 20, y);
      y += lineHeight;
    });

    // Add decorative line at bottom
    doc.setDrawColor(...COLORS.sage);
    doc.setLineWidth(0.5);
    doc.line(20, doc.internal.pageSize.height - 25, 190, doc.internal.pageSize.height - 25);
  });

  // Add page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i);
  }

  return doc;
}

// ────────────────────────────────────────────────────────────────────────────
// LEGACY SUMMARY EXPORT
// ────────────────────────────────────────────────────────────────────────────

interface LegacySummary {
  userName: string;
  voiceMessagesCount: number;
  memoriesCount: number;
  storiesCount: number;
  familyMembersCount: number;
  financeItemsCount: number;
  insuranceItemsCount: number;
  emergencyContacts: Array<{ name: string; phone: string; relationship: string }>;
  trustees: Array<{ name: string; email: string }>;
  legacyInstructions?: string;
}

export function exportLegacySummaryToPDF(
  summary: LegacySummary,
  options: ExportOptions = {}
): jsPDF {
  const doc = new jsPDF();
  let y = addHeader(
    doc,
    "Legacy Summary",
    "Complete Overview",
    summary.userName
  );

  // Overview Section
  y = addSectionTitle(doc, "Digital Legacy Overview", y);

  const overviewData = [
    ["Voice Messages", summary.voiceMessagesCount.toString()],
    ["Memories & Photos", summary.memoriesCount.toString()],
    ["Life Stories", summary.storiesCount.toString()],
    ["Family Members", summary.familyMembersCount.toString()],
    ["Financial Accounts", summary.financeItemsCount.toString()],
    ["Insurance Policies", summary.insuranceItemsCount.toString()],
  ];

  autoTable(doc, {
    startY: y,
    body: overviewData,
    theme: "plain",
    styles: {
      fontSize: 11,
      cellPadding: 4,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 80 },
      1: { halign: "right", cellWidth: 40 },
    },
  });

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // Emergency Contacts
  if (summary.emergencyContacts.length > 0) {
    y = addSectionTitle(doc, "Emergency Contacts", y);

    const contactsData = summary.emergencyContacts.map((c) => [
      c.name,
      c.relationship,
      c.phone,
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Name", "Relationship", "Phone"]],
      body: contactsData,
      theme: "striped",
      headStyles: {
        fillColor: COLORS.sage,
        textColor: 255,
      },
      styles: { fontSize: 10 },
    });

    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  }

  // Trustees
  if (summary.trustees.length > 0) {
    y = addSectionTitle(doc, "Designated Trustees", y);

    const trusteesData = summary.trustees.map((t) => [t.name, t.email]);

    autoTable(doc, {
      startY: y,
      head: [["Name", "Email"]],
      body: trusteesData,
      theme: "striped",
      headStyles: {
        fillColor: COLORS.sage,
        textColor: 255,
      },
      styles: { fontSize: 10 },
    });

    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  }

  // Legacy Instructions
  if (summary.legacyInstructions) {
    if (y > 200) {
      doc.addPage();
      y = 20;
    }

    y = addSectionTitle(doc, "Legacy Instructions", y);

    doc.setTextColor(...COLORS.text);
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(summary.legacyInstructions, 170);
    doc.text(lines, 20, y);
  }

  // Add page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i);
  }

  return doc;
}
